//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.BookServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookInfo", Namespace="http://schemas.datacontract.org/2004/07/Server")]
    [System.SerializableAttribute()]
    public partial class BookInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BorrowDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReturnDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BorrowDate {
            get {
                return this.BorrowDateField;
            }
            set {
                if ((this.BorrowDateField.Equals(value) != true)) {
                    this.BorrowDateField = value;
                    this.RaisePropertyChanged("BorrowDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Info {
            get {
                return this.InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoField, value) != true)) {
                    this.InfoField = value;
                    this.RaisePropertyChanged("Info");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReturnDate {
            get {
                return this.ReturnDateField;
            }
            set {
                if ((this.ReturnDateField.Equals(value) != true)) {
                    this.ReturnDateField = value;
                    this.RaisePropertyChanged("ReturnDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/Server")]
    [System.SerializableAttribute()]
    public partial class Status : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BookServiceReference.IServiceDemo")]
    public interface IServiceDemo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDemo/ListOfBorrowedItems", ReplyAction="http://tempuri.org/IServiceDemo/ListOfBorrowedItemsResponse")]
        string ListOfBorrowedItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDemo/ListOfBorrowedItems", ReplyAction="http://tempuri.org/IServiceDemo/ListOfBorrowedItemsResponse")]
        System.Threading.Tasks.Task<string> ListOfBorrowedItemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDemo/getBorrowedBooks", ReplyAction="http://tempuri.org/IServiceDemo/getBorrowedBooksResponse")]
        string getBorrowedBooks(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDemo/getBorrowedBooks", ReplyAction="http://tempuri.org/IServiceDemo/getBorrowedBooksResponse")]
        System.Threading.Tasks.Task<string> getBorrowedBooksAsync(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDemo/GetBookInfo", ReplyAction="http://tempuri.org/IServiceDemo/GetBookInfoResponse")]
        Client.BookServiceReference.BookInfo GetBookInfo(int bootID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDemo/GetBookInfo", ReplyAction="http://tempuri.org/IServiceDemo/GetBookInfoResponse")]
        System.Threading.Tasks.Task<Client.BookServiceReference.BookInfo> GetBookInfoAsync(int bootID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDemo/BorrowedBook", ReplyAction="http://tempuri.org/IServiceDemo/BorrowedBookResponse")]
        Client.BookServiceReference.Status BorrowedBook(int bootID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDemo/BorrowedBook", ReplyAction="http://tempuri.org/IServiceDemo/BorrowedBookResponse")]
        System.Threading.Tasks.Task<Client.BookServiceReference.Status> BorrowedBookAsync(int bootID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDemoChannel : Client.BookServiceReference.IServiceDemo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDemoClient : System.ServiceModel.ClientBase<Client.BookServiceReference.IServiceDemo>, Client.BookServiceReference.IServiceDemo {
        
        public ServiceDemoClient() {
        }
        
        public ServiceDemoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDemoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDemoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDemoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ListOfBorrowedItems() {
            return base.Channel.ListOfBorrowedItems();
        }
        
        public System.Threading.Tasks.Task<string> ListOfBorrowedItemsAsync() {
            return base.Channel.ListOfBorrowedItemsAsync();
        }
        
        public string getBorrowedBooks(int userID) {
            return base.Channel.getBorrowedBooks(userID);
        }
        
        public System.Threading.Tasks.Task<string> getBorrowedBooksAsync(int userID) {
            return base.Channel.getBorrowedBooksAsync(userID);
        }
        
        public Client.BookServiceReference.BookInfo GetBookInfo(int bootID) {
            return base.Channel.GetBookInfo(bootID);
        }
        
        public System.Threading.Tasks.Task<Client.BookServiceReference.BookInfo> GetBookInfoAsync(int bootID) {
            return base.Channel.GetBookInfoAsync(bootID);
        }
        
        public Client.BookServiceReference.Status BorrowedBook(int bootID) {
            return base.Channel.BorrowedBook(bootID);
        }
        
        public System.Threading.Tasks.Task<Client.BookServiceReference.Status> BorrowedBookAsync(int bootID) {
            return base.Channel.BorrowedBookAsync(bootID);
        }
    }
}
