//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.BookServiceReference3 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/Server")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BookIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.BookServiceReference3.BookInfo InfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.BookServiceReference3.Status StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BookID {
            get {
                return this.BookIDField;
            }
            set {
                if ((this.BookIDField.Equals(value) != true)) {
                    this.BookIDField = value;
                    this.RaisePropertyChanged("BookID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientID {
            get {
                return this.ClientIDField;
            }
            set {
                if ((this.ClientIDField.Equals(value) != true)) {
                    this.ClientIDField = value;
                    this.RaisePropertyChanged("ClientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.BookServiceReference3.BookInfo Info {
            get {
                return this.InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoField, value) != true)) {
                    this.InfoField = value;
                    this.RaisePropertyChanged("Info");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.BookServiceReference3.Status Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookInfo", Namespace="http://schemas.datacontract.org/2004/07/Server")]
    [System.SerializableAttribute()]
    public partial class BookInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BorrowDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReturnDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BorrowDate {
            get {
                return this.BorrowDateField;
            }
            set {
                if ((this.BorrowDateField.Equals(value) != true)) {
                    this.BorrowDateField = value;
                    this.RaisePropertyChanged("BorrowDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Info {
            get {
                return this.InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoField, value) != true)) {
                    this.InfoField = value;
                    this.RaisePropertyChanged("Info");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReturnDate {
            get {
                return this.ReturnDateField;
            }
            set {
                if ((this.ReturnDateField.Equals(value) != true)) {
                    this.ReturnDateField = value;
                    this.RaisePropertyChanged("ReturnDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/Server")]
    [System.SerializableAttribute()]
    public partial class Status : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsBorrowedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBorrowed {
            get {
                return this.IsBorrowedField;
            }
            set {
                if ((this.IsBorrowedField.Equals(value) != true)) {
                    this.IsBorrowedField = value;
                    this.RaisePropertyChanged("IsBorrowed");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BookServiceReference3.IServiceDemo")]
    public interface IServiceDemo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDemo/ListOfBorrowedItems", ReplyAction="http://tempuri.org/IServiceDemo/ListOfBorrowedItemsResponse")]
        Client.BookServiceReference3.Book[] ListOfBorrowedItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDemo/ListOfBorrowedItems", ReplyAction="http://tempuri.org/IServiceDemo/ListOfBorrowedItemsResponse")]
        System.Threading.Tasks.Task<Client.BookServiceReference3.Book[]> ListOfBorrowedItemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDemo/getBorrowedBooks", ReplyAction="http://tempuri.org/IServiceDemo/getBorrowedBooksResponse")]
        Client.BookServiceReference3.Book[] getBorrowedBooks(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDemo/getBorrowedBooks", ReplyAction="http://tempuri.org/IServiceDemo/getBorrowedBooksResponse")]
        System.Threading.Tasks.Task<Client.BookServiceReference3.Book[]> getBorrowedBooksAsync(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDemo/GetBookInfo", ReplyAction="http://tempuri.org/IServiceDemo/GetBookInfoResponse")]
        Client.BookServiceReference3.BookInfo GetBookInfo(int bookID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDemo/GetBookInfo", ReplyAction="http://tempuri.org/IServiceDemo/GetBookInfoResponse")]
        System.Threading.Tasks.Task<Client.BookServiceReference3.BookInfo> GetBookInfoAsync(int bookID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDemo/BorrowedBook", ReplyAction="http://tempuri.org/IServiceDemo/BorrowedBookResponse")]
        Client.BookServiceReference3.Status BorrowedBook(int bookID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDemo/BorrowedBook", ReplyAction="http://tempuri.org/IServiceDemo/BorrowedBookResponse")]
        System.Threading.Tasks.Task<Client.BookServiceReference3.Status> BorrowedBookAsync(int bookID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDemoChannel : Client.BookServiceReference3.IServiceDemo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDemoClient : System.ServiceModel.ClientBase<Client.BookServiceReference3.IServiceDemo>, Client.BookServiceReference3.IServiceDemo {
        
        public ServiceDemoClient() {
        }
        
        public ServiceDemoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDemoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDemoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDemoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client.BookServiceReference3.Book[] ListOfBorrowedItems() {
            return base.Channel.ListOfBorrowedItems();
        }
        
        public System.Threading.Tasks.Task<Client.BookServiceReference3.Book[]> ListOfBorrowedItemsAsync() {
            return base.Channel.ListOfBorrowedItemsAsync();
        }
        
        public Client.BookServiceReference3.Book[] getBorrowedBooks(int userID) {
            return base.Channel.getBorrowedBooks(userID);
        }
        
        public System.Threading.Tasks.Task<Client.BookServiceReference3.Book[]> getBorrowedBooksAsync(int userID) {
            return base.Channel.getBorrowedBooksAsync(userID);
        }
        
        public Client.BookServiceReference3.BookInfo GetBookInfo(int bookID) {
            return base.Channel.GetBookInfo(bookID);
        }
        
        public System.Threading.Tasks.Task<Client.BookServiceReference3.BookInfo> GetBookInfoAsync(int bookID) {
            return base.Channel.GetBookInfoAsync(bookID);
        }
        
        public Client.BookServiceReference3.Status BorrowedBook(int bookID) {
            return base.Channel.BorrowedBook(bookID);
        }
        
        public System.Threading.Tasks.Task<Client.BookServiceReference3.Status> BorrowedBookAsync(int bookID) {
            return base.Channel.BorrowedBookAsync(bookID);
        }
    }
}
